version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - devops_net

volumes:
  jenkins_data:
    driver: local

networks:
  devops_net:
    driver: bridge