version: "3.8"
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devops_net

volumes:
  nexus_data:
    driver: local

networks:
  devops_net:
    driver: bridge